//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelodyPlus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MelodyPlus.Resources.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode?.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Viewer.
        /// </summary>
        internal static string OpenViewer {
            get {
                return ResourceManager.GetString("OpenViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Album Name.
        /// </summary>
        internal static string ShowAlbumName {
            get {
                return ResourceManager.GetString("ShowAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Playlist Name.
        /// </summary>
        internal static string ShowPlaylistName {
            get {
                return ResourceManager.GetString("ShowPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Playlist Share Code.
        /// </summary>
        internal static string ShowPlaylistShareCode {
            get {
                return ResourceManager.GetString("ShowPlaylistShareCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Progress.
        /// </summary>
        internal static string ShowProgress {
            get {
                return ResourceManager.GetString("ShowProgress", resourceCulture);
            }
        }
    }
}
